//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataOverTime
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public float MemoryMB { get; set; }
        public Nullable<int> Business_Id { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
