//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class DataOverTime
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public float MemoryMB { get; set; }
        public Nullable<int> Business_Id { get; set; }
    
        public virtual Business Business { get; set; }
=======
    /// <summary>
    /// Creates an instance of the data over time when called upon
    /// </summary>
    public class DataOverTime
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the date time.
        /// </summary>
        /// <value>
        /// The date time.
        /// </value>
        [Required]
        public DateTime DateTime { get; set; }

        /// <summary>
        /// Gets or sets the memory mb.
        /// </summary>
        /// <value>
        /// The memory mb.
        /// </value>
        [Required]
        public float MemoryMB { get; set; }

        /// <summary>
        /// Gets or sets the business.
        /// </summary>
        /// <value>
        /// The business.
        /// </value>
        public Business Business { get; set; }
>>>>>>> parent of ae2ad3a... Took out XML Comments
    }
}
