//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public System.DateTime DateTime { get; set; }
=======
    /// <summary>
    /// Creates an instance of the error when called upon
    /// </summary>
    public class Error
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        /// <value>
        /// The type.
        /// </value>
        [Required]
        [MaxLength(100)]
        [MinLength(5)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the date time.
        /// </summary>
        /// <value>
        /// The date time.
        /// </value>
        [Required]
        public DateTime DateTime { get; set; }
>>>>>>> parent of ae2ad3a... Took out XML Comments
    }
}
