//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime DateTimeSend { get; set; }
        public System.DateTime DateTimeViewed { get; set; }
        public string ContentString { get; set; }
        public string ContentImagePath { get; set; }
        public string Recipient_Id { get; set; }
        public string Sender_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
