//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime DateTimeSend { get; set; }
        public System.DateTime DateTimeViewed { get; set; }
        public string ContentString { get; set; }
        public string ContentImagePath { get; set; }
        public string Recipient_Id { get; set; }
        public string Sender_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
=======
    /// <summary>
    /// Creates an instance of the message when called upon
    /// </summary>
    public class Message
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the date time send.
        /// </summary>
        /// <value>
        /// The date time send.
        /// </value>
        [Required]
        public DateTime DateTimeSend { get; set; }

        /// <summary>
        /// Gets or sets the date time viewed.
        /// </summary>
        /// <value>
        /// The date time viewed.
        /// </value>
        public DateTime DateTimeViewed { get; set; }


        /// <summary>
        /// Gets or sets the content string.
        /// </summary>
        /// <value>
        /// The content string.
        /// </value>
        public string ContentString { get; set; }


        /// <summary>
        /// Gets or sets the content image path.
        /// </summary>
        /// <value>
        /// The content image path.
        /// </value>
        public string ContentImagePath { get; set; }


        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        /// <value>
        /// The sender.
        /// </value>
        public ApplicationUser Sender { get; set; }

        /// <summary>
        /// Gets or sets the recipient.
        /// </summary>
        /// <value>
        /// The recipient.
        /// </value>
        public ApplicationUser Recipient { get; set; }
>>>>>>> parent of ae2ad3a... Took out XML Comments
    }
}
