//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int Id { get; set; }
        public string PassString { get; set; }
        public bool Valid { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
=======
    /// <summary>
    /// Creates an instance of the password when called upon
    /// </summary>
    public class Password
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the pass string.
        /// </summary>
        /// <value>
        /// The pass string.
        /// </value>
        [Required]
        [MaxLength(20)] [MinLength(8)]
        [RegularExpression("(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9])$", ErrorMessage = "Password must have a letter, a number and no special characters.")]
        public string PassString { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="Password"/> is valid.
        /// </summary>
        /// <value>
        ///   <c>true</c> if valid; otherwise, <c>false</c>.
        /// </value>
        [Required]
        public bool Valid { get; set; }

        //Foreign Key
        /// <summary>
        /// Gets or sets the user.
        /// </summary>
        /// <value>
        /// The user.
        /// </value>
        public ApplicationUser User { get; set; }


>>>>>>> parent of ae2ad3a... Took out XML Comments
    }
}
