//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSRDBEntities : DbContext
    {
        public RSRDBEntities()
            : base("name=RSRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<BusinessUserType> BusinessUserTypes { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<DataOverTime> DataOverTimes { get; set; }
        public virtual DbSet<DataTransferRate> DataTransferRates { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Update> Updates { get; set; }
        public virtual DbSet<UserInterest> UserInterests { get; set; }
    }
}
