//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
<<<<<<< HEAD
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public float Amount { get; set; }
        public float VAT { get; set; }
        public float Total { get; set; }
        public System.DateTime DateSent { get; set; }
        public System.DateTime DateRefunded { get; set; }
        public Nullable<int> Recipient_Id { get; set; }
        public Nullable<int> Sender_Id { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Business Business1 { get; set; }
=======
    /// <summary>
    /// When called upon, instanciates the transaction class
    /// </summary>
    public class Transaction
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        /// <value>
        /// The type.
        /// </value>
        [Required]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets the amount.
        /// </summary>
        /// <value>
        /// The amount.
        /// </value>
        [Required]
        public float Amount { get; set; }

        /// <summary>
        /// Gets or sets the vat.
        /// </summary>
        /// <value>
        /// The vat.
        /// </value>
        [Required]
        public float VAT { get; set; }

        /// <summary>
        /// Gets or sets the total.
        /// </summary>
        /// <value>
        /// The total.
        /// </value>
        [Required]
        public float Total { get; set; }

        /// <summary>
        /// Gets or sets the date sent.
        /// </summary>
        /// <value>
        /// The date sent.
        /// </value>
        [Required]
        public DateTime DateSent { get; set; }

        /// <summary>
        /// Gets or sets the date refunded.
        /// </summary>
        /// <value>
        /// The date refunded.
        /// </value>
        public DateTime DateRefunded { get; set; }





        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        /// <value>
        /// The sender.
        /// </value>
        public Business Sender { get; set; }


        /// <summary>
        /// Gets or sets the recipient.
        /// </summary>
        /// <value>
        /// The recipient.
        /// </value>
        public Business Recipient { get; set; }
>>>>>>> parent of ae2ad3a... Took out XML Comments
    }
}
