//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadySetResource.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public float Amount { get; set; }
        public float VAT { get; set; }
        public float Total { get; set; }
        public System.DateTime DateSent { get; set; }
        public System.DateTime DateRefunded { get; set; }
        public Nullable<int> Recipient_Id { get; set; }
        public Nullable<int> Sender_Id { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Business Business1 { get; set; }
    }
}
